config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'projects/show_mario'
  get 'projects/show_ttt'

  root 'pages#about_me' 
  get 'pages/about_me', :path => "about_me"

  get 'pages/my_work', :path => "my_work"

  get 'pages/resume', :path => "resume"

  get 'pages/skills', :path => "skills"

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_me
  end

  def my_work
    

  end

  def resume

  end

  def skills

  end

  def contact_me

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index	
  end
  def show_mario
  end
  def show_ttt
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.erb
<div class="sidebar">
	<br>
	<div id="home_txt"><%= link_to 'Home', root_path, class: 'sidelink' %></div><br>
	<div id="resume_txt"><%= link_to 'Resume', pages_resume_path, class: 'sidelink' %></div><br>
	<div id="mywork_txt"><%= link_to 'My Work', projects_index_path, class: 'sidelink' %></div><br>
	<div id="skills_txt"><%= link_to 'Skills', pages_skills_path, class: 'sidelink' %></div><br>
	<div class="iconz">
		<%= link_to 'https://www.facebook.com/ilia.reingold?ref=tn_tnmn' do %>
		<%= image_tag('fbook.png', :id => 'fbook') %>
		<% end %>
		<%= link_to 'https://github.com/ilrein' do %>
		<%= image_tag('ghub.png', :id => 'ghub') %>
		<% end %>
	</div>
	<div class="iconz">
		<%= link_to '#' do %>
		<%= image_tag('twitter.png', :id => 'twitter') %>
		<% end %>
		<%= link_to '#' do %>
		<%= image_tag('linkedin.png', :id => 'linkedin') %>
		<% end %>
	</div>
</div>
<script>
	//$('.sidebar').bigtext();
	tl = new TimelineLite();
	tl2 = new TimelineLite();
	tl3 = new TimelineLite();
	tl4 = new TimelineLite();

	tl5 = new TimelineLite();
	tl6 = new TimelineLite();
	tl7 = new TimelineLite();
	tl8 = new TimelineLite();

	//mouse hover animations
	// $('#home_txt').on("mouseenter", function(){
	// 	tl.to($(this), 0.2, {css:{fontSize:"40px"}});
	// 	tl.restart();
	// });
	// $('#home_txt').on("mouseleave", function(){
	// 	tl.reverse();
	// });
	// //...........................................

	// $('#resume_txt').on("mouseenter", function(){
	// 	tl2.to($(this), 0.2, {css:{fontSize:"40px"}});
	// 	tl2.restart();
	// });
	// $('#resume_txt').on("mouseleave", function(){
	// 	tl2.reverse();
	// });
	// //   .......................................

	// $('#mywork_txt').on("mouseenter", function(){
	// 	tl3.to($(this), 0.2, {css:{fontSize:"40px"}});
	// 	tl3.restart();
	// });
	// $('#mywork_txt').on("mouseleave", function(){
	// 	tl3.reverse();
	// });
	// //...........................................
	// $('#skills_txt').on("mouseenter", function(){
	// 	tl4.to($(this), 0.2, {css:{fontSize:"40px"}});
	// 	tl4.restart();
	// });
	// $('#skills_txt').on("mouseleave", function(){
	// 	tl4.reverse();
	// });
	// //...........................................
	$('#fbook').on("mouseenter", function(){
		tl5.to($(this), 60, {rotation:360});
		tl5.resume();
	});
	$('#fbook').on("mouseleave", function(){
		tl5.pause();
	});
	//...........................................
	$('#ghub').on("mouseenter", function(){
		tl6.to($(this), 60, {rotation:360});
		tl6.resume();
	});
	$('#ghub').on("mouseleave", function(){
		tl6.pause();
	});
	//...........................................
	$('#twitter').on("mouseenter", function(){
		tl7.to($(this), 60, {rotation:360});
		tl7.resume();
	});
	$('#twitter').on("mouseleave", function(){
		tl7.pause();
	});
	//...........................................
	$('#linkedin').on("mouseenter", function(){
		tl8.to($(this), 60, {rotation:360});
		tl8.resume();
	});
	$('#linkedin').on("mouseleave", function(){
		tl8.pause();
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Portfolio</title>
	<script src="//www.google.com/jsapi"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
	<link href='http://fonts.googleapis.com/css?family=Kreon' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>

	<%= render 'layouts/footer' %>
</head>
<body>
	<div class="container1">
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about_me.html.erb
<style>
  #headshot {
    border-style: solid;
    width: 100%;
  }
  .home_description {
  }
  #hello {
    position: relative;
    font-family: 'Kreon', serif;
    text-align: center;
    font-size: 200%;
  }
  .homez {
    overflow: hidden;
  }
</style>
<div class='homez'>
<%= image_tag('ir.jpg', :id => 'headshot') %>
<div class="home_description">
 <%= image_tag('ss1.png', :id => 'headshot') %>
</div>

app/views/pages/contact_me.html.erb
<div class="contactme">
<h1>Pages#contact_me</h1>
<p>Find me in app/views/pages/contact_me.html.erb</p>
</div>

app/views/pages/marioworld.html.erb
<div class="container">
	<script>
	$(document).ready( animateBackground );
	
	function animateBackground(){

	//instanstiated variables/objects
	
	var boo1 = $("#boo1");
	var boo2 = $("#boo2");
	$('#boo3').hide();
	var boo4 = $('.boo4');
	var floor = $('#wooden_floor');
	var hills = $('#smiley_hills');
	var boxes = $('#question_boxes');
	var boxes2 = $('#question_boxes2');
	var blocks = $('#blocks');
	var clouds = $('#clouds');
	var words = $('.words');
	var bg_hills = $('#bg_hills');
	var paused = false;
	var hide = new TimelineLite();
	var bb = new TimelineLite();
	var bb2 = new TimelineLite();
	var bb3 = new TimelineLite();
	var bb4 = new TimelineLite();
	var bb5 = new TimelineLite();
	var skillz = new TimelineLite();
	var b4s = b4s;

		//mouse follow

		$(document).on('mousemove', moveBoo);
		$(document).on('mousemove', mouseSpot);

		function moveBoo(e){
			TweenLite.to(boo4, 4, {css:{left: (e.pageX - 270), top: e.pageY}});
			b4s = boo4.position();
			if (b4s.left < (e.pageX- 270)) {
				$('.boo4').addClass('flipped');
			} else {
				$('.boo4').removeClass('flipped');
			} 
		}

		function mouseSpot(e) {

		}

		// helper boo

		// $('.boo4').on('click', function(){
		// 	$.ajax({
		// 		url: 'skills',
		// 		type: 'GET',
		// 		dataType: 'html'
		// 	}).done(function(data){
		// 		$('.container').append(data);
				
		// 	});
		// });

		$('.boo4').on("mouseenter", function(e){
			if (b4s.left < e.pageX) {
				$('.boo4').addClass('boo4_closed');
			}
		});

		$('.boo4').on("mouseleave", function(){
			$('.boo4').removeClass('boo4_closed');
		});

		// hide all the images

		hide.to(floor, 0.1, {
			opacity:0,
			onComplete:initFloor
		});

		hide.to(words, 0.001, {
			scale:0.01
		});

		hide.to(hills, 0.1, {
			opacity:0
		});

		hide.to(boxes, 0.1, {
			opacity:0
		});

		hide.to(boxes2, 0.1, {
			opacity:0
		});

		hide.to(blocks, 0.1, {
			left:"1000px"
		});

		hide.to(clouds, 0.001, {
			scale:0.01
		});

		hide.to(cloud, 0.001, {
			scale:0.01
		});

		hide.to(bg_hills, 0.001, {
			top:"-522px"
		});

		//chain the animations!

		function initFloor() {
			TweenLite.to(floor, 2.3, {
				opacity:1,
				onComplete:initHills
			});
		}

		function initHills() {
			TweenLite.to(hills, 1.2, {
				opacity:1,
				left:"50px",
				ease: Elastic.easeIn,
				onComplete:initBoxes
			});
			TweenLite.from(words, 1.2, {
				opacity:1,
				ease: Bounce.easeIn,
				onComplete:initBoxes
			});
			TweenLite.to(words, 1.2, {
				opacity:1,
				scale:1
			});
		}

		function initBoxes() {
			TweenLite.from(boxes, 2, {
				opacity:0.75,
				left:"50px",
				ease: Bounce.easeIn,
				onComplete:keepBoxes1
			});

			TweenLite.from(boxes2, 2.4, {
				opacity:1,
				rotation:360,
				onComplete:keepBoxes2
			});
		}

		function keepBoxes1() {
			TweenLite.to(boxes, 2.1, {
				opacity:1,
				onComplete:initBlocks
			});
		}
		function keepBoxes2() {
			TweenLite.to(boxes2, 1, {
				opacity:1,
				onComplete:initClouds
			});
		}

		function initClouds() {
			TweenLite.to(clouds, 1, {
				scale:1,
				ease: Bounce,
				onComplete:initCloud
			});
		}

		function initCloud() {
			TweenLite.to(cloud, 1, {
				scale:1,
				ease: Bounce,
				onComplete:initBgHills
			});
		}
		function initBgHills() {
			bb5.to(bg_hills, 1, {
				top:"-=263px",
				ease: Bounce.easeOut
			});
			//bb5.reverse();
		}
		function initBlocks() {
			TweenLite.to(blocks, 1, {
				left:"-=1000px",
				ease: Bounce,
				onComplete:keepBlocks
			});
		}
		function keepBlocks() {
			TweenLite.to(blocks, 1.4, {
				opacity:1
			});
		}

		// onload animations

		TweenMax.to(s1, 3, {
			scale:1.2,
			opacity:2,
			repeat:-1,
			ease: SlowMo.ease.config(0.3, 0.6, true)
		});

		tween1 = TweenLite.to(boo1, 100, {
			left:"3000px"
		});

		tween2 = TweenMax.to(boo2, 6, {
			left:"-200px",
			opacity:0,
			repeat:-1,
			ease:SlowMo.ease.config(0.3, 0.6, true)
		});

		TweenLite.to(boo3, 110, {
			left:"5000px"
		});

		// click animations

		$('#question_boxes').on('click', function(){
			bb.to(boxes, 1.1, {
				scale:0.8,
				opacity:0.5
			});
			bb.reverse();
		});

		$('#question_boxes2').on('click', function(){
			bb2.to(boxes2, 1.1, {
				scale:0.8,
				opacity:0.5,
				rotation:-360
			});
			bb2.reverse();
		});

		$('#smiley_hills').on('click', function(){
			bb3.to(hills, 2.5, {
				scale:1.4
			});
			bb3.reverse();
		});

		$('#blocks').on('click', function(){
			bb4.to(blocks, 2.5, {
				scale:1.4
			});
			bb4.reverse();
		});

		$('#boo4').click(function(){
			TweenLite.to(boo4, 4, {
				opacity:0.25
			});
		});

		$('#clouds').on('click', function(){
			var selected = $(this);
			rotate(selected);
			rt.time(0);
		});

		// utility functions

		var rt = new TimelineLite();

		function rotate(selected){
			rt.to(selected, 2, {
				rotation:360
			});
		}

		// end of utility

		//click functions:

		$('#cloud').on('click', function(){
			$('#cloud').animate({
				left:"+=50"
			});
		});

		$('#boo1').click(function(){
			$('#boo3').fadeIn("slow");
			TweenLite.to(boo1, 1.6,{
				top:'+=40px', 
				ease:Strong.easeOut
			});
			$('#boo1').fadeOut("slow");
		});

		$('#boo3').click(function(){
			$('#boo1').fadeIn("slow");
			TweenLite.to(boo3, 1.6,{
				top:'-=40px', 
				ease:Strong.easeOut
			});
			$('#boo3').fadeOut("slow");
		});

		$('#boo2').click(function(){
			TweenLite.to(boo2, 1.6,{
				top:'+=40px', 
				ease:Strong.easeOut

			});
			TweenLite.to(boo2, 15, {
				left:"-200px",
				opacity:0,
				ease:SlowMo.ease.config(0.3, 0.6, true)
			});
		});

		// key press events

		$(document).keypress(function(event){
			if (event.which == 112) {
				if (paused == false) {
					hide.pause();
					paused = true;	
				} else {
					hide.resume();
					paused = false;	
				}
			}
		});

		$(document).keypress(function(event){
			if (event.which == 114) {
				hide.restart();
			}
		});
		
	};
	</script>		
	<%= image_tag('blue_bg.jpg', id: 'bg') %>
	<div class="draft">
		<div id="boo1"></div>
		<div id="boo2"></div>
		<div id="boo3"></div>
		<div class="boo4"></div>		
	</div>

	<div id="wooden_floor">
		<div id="smiley_hills"></div>
		<div id="question_boxes"></div>
		<div id="question_boxes2"></div>
		<div id="blocks"></div>
		<div id="clouds"></div>
		<div id="cloud"></div>
		<div id="bg_hills"></div>
	</div>
	<div class="words">
		<p id="s1">Welcome to: Mario's World!</p>
	</div>
	<div id="dialog">

	</div>
</div>

app/views/pages/resume.html.erb
<div class='resume'>
	<div id="interlude">Resume::Ilia Reingold</div>
	<div id="notes">
		<h3 id="cg">Career Goals:</h3>
		<div class="inner_details">
			My goal is to begin a career as a junior web developer. I want to design and develop amazing and beautiful web apps.
		</div>
		<div class="inner_details">
			I want to work in a learning orientated environment, and blossom from a junior level developer.
		</div>
	</div>
	<div id="experience">
		<h3 id='pwork'>Previous Work Experience:</h3>
		<div class="work_details">
			<div class='upper_work_details'>
				<%= image_tag('stadia.png', id: 'stadia') %> 
				<h6 id='stadia_role'>Accounting/Operations Assistant @ Stadia Industries (Aug. 2014/May 2015)</h6>
			</div><br>
			<div class='mid_work_details'>
				<ul>
					<li>Aided CFO with time consuming routine accounting tasks</li>
					<li class='indented'>Learned the fundamentals of practical accounting</li>
					<li>Helped Director of Operations manage daily work flow, closing customers, issuing POs, creating high quality reports for clients</li>
					<li class='indented'>Observed the art of management/leadership running a team of 20 people</li>
					<li class='indented'>Watched crisp professionalism dealing with difficult clients</li>
				</ul>

				<div id="work_details_nexttier">	
					<%= image_tag('humber.jpg', id: 'humber1') %> 			
					<h6 id='humber_role'>English Tutor @ Humber College</h6>
				</div><br>
				<div id='midlow_work_details'>
					<ul>
						<li>Tutored hundreds of students, of all ethnic backgrounds, over 3 years</li>
						<li class='indented'>Mastered the art of teaching, establishing rapport, clear communication</li>
						<li>Personally developed a crisp, effective, highly persuasive writing ability</li>
					</ul>
				</div>	
			</div>
		</div>
	</div>

app/views/pages/skills.html.erb
<div class="mastery">
	<div id="interlude">Technologies I Plan to Master:</div><br>
	<table>
		<td><div id="html5"><%= image_tag('html5.png') %></div></td>
		<td><div id="CSS3"><%= image_tag('CSS3.png') %></div></td>
		<td><div id="js"><%= image_tag('js.png') %></div></td>
		<td><div id="ruby"><%= image_tag('ruby.png') %></div></td>
		<td><div id="rails"><%= image_tag('rails.png') %></div></td>
		<td><div id="ajs"><%= image_tag('ajs.png') %></div></td>

	</table><br><br>
</div>
<div class="skills">
	<div id="interlude2">My Knowledge:</div><br>
	<div id="chart-3" style="height: 300px;"></div>
</div>
<div class="wakingtime">
	<div id="interlude3">How I spend my waking time (hours):</div><br>
	<div id="chart-1" style="height: 300px;"></div>
</div>
<style>
body{
  overflow-y: scroll;
  overflow-x:hidden;
}
</style>
<script>
$(document).ready(function(){
	 t = new TimelineLite();
  t2 = new TimelineLite();
  t3 = new TimelineLite();
  t4 = new TimelineLite();
  t5 = new TimelineLite();
  t6 = new TimelineLite();
  t7 = new TimelineLite();
  t8 = new TimelineLite();
  t9 = new TimelineLite();

  $('#interlude').mouseenter(function(){
    t7.to($(this), 0.7, {scale:1.2});
    t7.restart();
  });
  $('#interlude').mouseleave(function(){
    t7.reverse();
  });
  $('#interlude2').mouseenter(function(){
    t8.to($(this), 0.7, {scale:1.2});
    t8.restart();
  });
  $('#interlude2').mouseleave(function(){
    t8.reverse();
  });
  $('#interlude3').mouseenter(function(){
    t9.to($(this), 0.7, {scale:1.2});
    t9.restart();
  });
  $('#interlude3').mouseleave(function(){
    t9.reverse();
  });

  $('#html5').mouseenter(function(){
    t.to($(this), 0.7, {scale:1.2});
    t.restart();
  });
  $('#html5').mouseleave(function(){
    t.reverse();
  });

  $('#CSS3').mouseenter(function(){
    t2.to($(this), 0.7, {scale:1.2});
    t2.restart();
  });
  $('#CSS3').mouseleave(function(){
    t2.reverse();
  });
  $('#js').mouseenter(function(){
    t3.to($(this), 0.7, {scale:1.2});
    t3.restart();
  });
  $('#js').mouseleave(function(){
    t3.reverse();
  });
  $('#ruby').mouseenter(function(){
    t4.to($(this), 0.7, {scale:1.2});
    t4.restart();
  });
  $('#ruby').mouseleave(function(){
    t4.reverse();
  });
  $('#rails').mouseenter(function(){
    t5.to($(this), 0.7, {scale:1.2});
    t5.restart();
  });
  $('#rails').mouseleave(function(){
    t5.reverse();
  });
  $('#ajs').mouseenter(function(){
    t6.to($(this), 0.7, {scale:1.2});
    t6.restart();
  });
  $('#ajs').mouseleave(function(){
    t6.reverse();
  });

  new Chartkick.PieChart("chart-1", [["Coding",7],["Eating",2],["Exercise",1],["Commuting",1.5],["Leisure",4]], {"colors": ["#BF495E", "#41A693", "#F2EC9B", "#D9CF48", "#D9583B"]});

  new Chartkick.BarChart("chart-3", [{name: "Hours Practised", data: [["HTML",200],["CSS",200],["JavaScript",300],["Ruby/Rails",300]]}, {name: "Remaining Hours to Mastery", data: [["HTML",4800],["CSS",4800],["JavaScript",4700],["Ruby/Rails",4700]]}], {'colors': ['#d54d72', 'pink'], max: 5000, stacked: true});

});
</script>

app/views/projects/index.html.erb
<style>
body {
	height:150%;
}
</style>
<div class="mywork">
	<div id="interlude4">My Work</div>

	<div class="project_section">
		
		<div id="mario_world_project">
			<%= link_to projects_show_mario_path do %>
			<div id="mario_world_project_topleft"></div><% end %>
			<div class="topright">
				<h5>Details</h5>
				<p class="project_description">
					<ul>
						<li>Built in March 2014</li>
						<li>3 days of effort</li>
						<li>Heavy use of jQuery & GSAP</li>
					</ul>
				</p>
			</div>
			<div class="project_bottom">
				<h5>Mario World</h5>
				<p class="project_description">
					This particular project was an adventure in the art of JavaScript animations. It was a lot of fun making things fly around the screen and animate on click. I realized during this exercise that front end appeals to me more than backend. It's just so much fun!
				</p>
			</div>
		</div>
		
		<div id="ttt_project">
			<%= link_to projects_show_ttt_path do %>
			<div id="ttt_project_top_left"></div><% end %>
			<div class="topright">
				<h5>Details</h5>
				<p class="project_description">
					<ul>
						<li>Built in early March 2014</li>
						<li>2 days of effort</li>
						<li>Vanilla JavaScript + some jQuery</li>
					</ul>
				</p>
			</div>
			<div class="project_bottom">
				<h5>Tic Tac Toe</h5>
				<p class="project_description">
					This was a class project as a follow up to learning the basics of JavaScript. The biggest challenge was figuring out how to program the logic to recognize a winner. I basically sat at my screen and stared at it for and hour and a half till I made it bend to my will.
				</p>
			</div>

			<!-- <div class id="crowdfunder_project">test</div> -->
			<!-- <div class id="final_project">test</div> -->
		</div>
	</div>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>